version: "3.9"

services:
  api:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -r requirements.txt && uvicorn fastapi_app:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  ui:
    image: node:18
    working_dir: /app
    command: bash -lc "npm install && npm start"
    volumes:
      - ./ui/webapp:/app
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
